# Generated by Django 5.2 on 2025-05-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='events_type',
            field=models.CharField(blank=True, choices=[('atividade', 'Atividade'), ('conferencia', 'Conferência'), ('culto', 'Culto'), ('especial', 'Especial'), ('estudo', 'Estudo'), ('reuniao', 'Reunião'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Tipo de Evento'),
        ),
    ]
