# Generated by Django 5.2 on 2025-04-26 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igrejas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('type', models.CharField(blank=True, choices=[('culto', 'Culto'), ('reuniao', 'Reunião'), ('especial', 'Especial')], max_length=50, null=True, verbose_name='Tipo de Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='igrejas.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['date', 'time'],
            },
        ),
    ]
