# Generated by Django 5.2 on 2025-05-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=255, verbose_name='Nome da Igreja Sede')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church_logo/', verbose_name='Logo da Igreja')),
                ('president_pastor_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Pastor Presidente')),
                ('treasurer_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Tesoureiro(a)')),
            ],
            options={
                'verbose_name': 'Configuração da Igreja',
                'verbose_name_plural': 'Configurações da Igreja',
            },
        ),
    ]
