# Generated by Django 5.2 on 2025-04-29 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0001_initial'),
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptism_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Batismo'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=15, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='member',
            name='origin_church',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Igreja de Origem'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo/Função'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('transferido', 'Transferido'), ('disciplina', 'Em Disciplina'), ('visitante', 'Visitante')], default='ativo', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='igrejas.church', verbose_name='Igreja Atual'),
        ),
    ]
