# Generated by Django 5.2 on 2025-04-26 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igrejas', '0001_initial'),
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mês/Ano de Referência')),
                ('tithes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dízimos')),
                ('offerings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ofertas')),
                ('projects', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Projetos Especiais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='igrejas.church', verbose_name='Igreja')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='membros.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Registro Financeiro Mensal',
                'verbose_name_plural': 'Registros Financeiros Mensais',
                'ordering': ['-month', 'church'],
            },
        ),
    ]
