# Generated by Django 5.2 on 2025-05-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Turma')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sala')),
                ('schedule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Horário')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de Alunos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to='members.member', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Turma da Escola Dominical',
                'verbose_name_plural': 'Turmas da Escola Dominical',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Data de Matrícula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='members.member', verbose_name='Membro (Aluno)')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.schoolclass', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['school_class', 'member__name'],
                'unique_together': {('member', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Aula')),
                ('present', models.BooleanField(default=False, verbose_name='Presente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.schoolclass', verbose_name='Turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Registro de Frequência',
                'verbose_name_plural': 'Registros de Frequência',
                'ordering': ['-date', 'student'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
