# Generated by Django 5.2 on 2025-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Data de Fundação')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='Horários')),
                ('church_type', models.CharField(blank=True, choices=[('sede', 'Sede'), ('filial', 'Filial')], max_length=10, null=True, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
                'ordering': ['name'],
            },
        ),
    ]
