# Generated by Django 5.2 on 2025-05-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ambos', 'Ambos')], default='ambos', max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao', 'Cartão'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('outro', 'Outro')], default='dinheiro', max_length=15, verbose_name='Forma de Pagamento')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='comprovantes/saidas/', verbose_name='Comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao', 'Cartão'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('outro', 'Outro')], default='dinheiro', max_length=15, verbose_name='Forma de Pagamento')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='comprovantes/entradas/', verbose_name='Comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(verbose_name='Mês/Ano de Referência')),
                ('tithes_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dízimos')),
                ('offerings_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ofertas')),
                ('projects_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Projetos Especiais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='churches.church', verbose_name='Igreja')),
            ],
            options={
                'verbose_name': 'Registro Financeiro Mensal',
                'verbose_name_plural': 'Registros Financeiros Mensais',
                'ordering': ['-reference_date', 'church'],
            },
        ),
    ]
