# Generated by Django 5.2 on 2025-05-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
        ('finances', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='members.member', verbose_name='Membro'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='expense',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='income',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church', verbose_name='Igreja'),
        ),
        migrations.AddField(
            model_name='income',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Membro'),
        ),
    ]
