# Generated by Django 5.2 on 2025-05-02 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='reference_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Mês/Ano de Referência'),
        ),
    ]
