# Generated by Django 5.2 on 2025-05-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, null=True, verbose_name='Sexo')),
                ('marital_status', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=15, null=True, verbose_name='Estado Civil')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Data de Batismo')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Data de Ingresso')),
                ('origin_church', models.CharField(blank=True, max_length=255, null=True, verbose_name='Igreja de Origem')),
                ('member_type', models.CharField(choices=[('membro', 'Membro'), ('visitante', 'Visitante'), ('obreiro', 'Obreiro')], default='membro', max_length=50, verbose_name='Tipo de Membro')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo/Função')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('transferido', 'Transferido'), ('disciplina', 'Em Disciplina'), ('visitante', 'Visitante')], default='ativo', max_length=15, verbose_name='Status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Foto')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='churches.church', verbose_name='Igreja Atual')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['name'],
            },
        ),
    ]
